"""Add PasswordResetToken table

Revision ID: 27b8726914b4
Revises: 8184ee23453b
Create Date: 2026-04-01 22:46:40.870036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27b8726914b4'
down_revision: Union[str, Sequence[str], None] = '8184ee23453b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PasswordResetToken',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Token', sa.String(length=999), nullable=False),
    sa.Column('ExpiresAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['UserID'], ['UserAccount.UserID'], ),
    sa.PrimaryKeyConstraint('UserID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PasswordResetToken')
    # ### end Alembic commands ###
