"""Remove old variables

Revision ID: 3ecb066e9af0
Revises: f74fa5de82a1
Create Date: 2026-03-20 21:56:33.289430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3ecb066e9af0'
down_revision: Union[str, Sequence[str], None] = 'f74fa5de82a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('HealthData_ibfk_1'),
                       'HealthData', type_='foreignkey')
    op.drop_column('HealthData', 'UserID')

    op.drop_column('UserAccount', 'FullName')
    # ### end Alembic commands ###


def downgrade() -> None:
    op.add_column('UserAccount', sa.Column(
        'FullName', sa.String(length=255), nullable=True))
    op.add_column('HealthData', sa.Column(
        'UserID', sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f('HealthData_ibfk_1'),
        'HealthData',
        'UserAccount',
        ['UserID'],
        ['UserID']
    )
    # ### end Alembic commands ###
