"""Change last name to family name

Revision ID: 6ddecd1fff22
Revises: 8184ee23453b
Create Date: 2026-03-25 17:55:19.634663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6ddecd1fff22'
down_revision: Union[str, Sequence[str], None] = '954c38c31b17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Patient', sa.Column(
        'FamilyName', sa.String(length=255), nullable=True))
    op.drop_column('Patient', 'LastName')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Patient', sa.Column(
        'LastName', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('Patient', 'FamilyName')
    # ### end Alembic commands ###
