"""Add patient and clinic tables

Revision ID: 954c38c31b17
Revises: 3ecb066e9af0
Create Date: 2026-03-21 09:42:50.673865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '954c38c31b17'
down_revision: Union[str, Sequence[str], None] = '3ecb066e9af0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Clinic',
                    sa.Column('ClinicID', sa.Integer(), nullable=False),
                    sa.Column('ClinicName', sa.String(
                        length=255), nullable=True),
                    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text(
                        'CURRENT_TIMESTAMP'), nullable=True),
                    sa.PrimaryKeyConstraint('ClinicID'),
                    sa.UniqueConstraint('ClinicName')
                    )
    op.create_table('Patient',
                    sa.Column('PatientID', sa.Integer(), nullable=False),
                    sa.Column('UserID', sa.Integer(), nullable=True),
                    sa.Column('GivenNames', sa.String(
                        length=255), nullable=True),
                    sa.Column('LastName', sa.String(
                        length=255), nullable=True),
                    sa.Column('Gender', sa.Integer(), nullable=True),
                    sa.Column('Weight', sa.Numeric(
                        precision=5, scale=2), nullable=True),
                    sa.Column('Height', sa.Numeric(
                        precision=5, scale=2), nullable=True),
                    sa.Column('DateOfBirth', sa.Date(), nullable=True),
                    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text(
                        'CURRENT_TIMESTAMP'), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['UserID'], ['UserAccount.UserID'], ),
                    sa.PrimaryKeyConstraint('PatientID')
                    )
    op.create_table('UserPatientAccess',
                    sa.Column('UserID', sa.Integer(), nullable=False),
                    sa.Column('PatientID', sa.Integer(), nullable=False),
                    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text(
                        'CURRENT_TIMESTAMP'), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['PatientID'], ['Patient.PatientID'], ),
                    sa.ForeignKeyConstraint(
                        ['UserID'], ['UserAccount.UserID'], ),
                    sa.PrimaryKeyConstraint('UserID', 'PatientID')
                    )
    op.drop_table('TestTable')
    op.add_column('HealthData', sa.Column(
        'PatientID', sa.Integer(), nullable=True))
    op.add_column('HealthData', sa.Column(
        'Stroke', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'HealthData', 'Patient',
                          ['PatientID'], ['PatientID'])
    op.drop_column('HealthData', 'MerchantID')
    op.add_column('UserAccount', sa.Column(
        'ClinicID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'UserAccount', 'Clinic',
                          ['ClinicID'], ['ClinicID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('UserPatientAccess', if_exists=True)
    op.execute('ALTER TABLE `HealthData` DROP FOREIGN KEY `HealthData_ibfk_1`')
    op.drop_column('HealthData', 'PatientID')
    op.drop_column('HealthData', 'Stroke')
    op.add_column('HealthData', sa.Column(
        'MerchantID', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.execute('ALTER TABLE `UserAccount` DROP FOREIGN KEY `UserAccount_ibfk_1`')
    op.drop_column('UserAccount', 'ClinicID')
    op.drop_table('Patient', if_exists=True)
    op.drop_table('Clinic', if_exists=True)
    op.create_table(
        'TestTable',
        sa.Column('TestID', mysql.INTEGER(),
                  autoincrement=True, nullable=False),
        sa.Column('Name', mysql.VARCHAR(length=255), nullable=True),
        sa.Column('Number', mysql.VARCHAR(length=20), nullable=True),
        sa.PrimaryKeyConstraint('TestID'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
