"""Test initial schema

Revision ID: a5633df15cee
Revises: 
Create Date: 2025-10-14 17:29:18.815736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a5633df15cee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('AccountRole', 'RoleName',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_index(op.f('RoleName'), table_name='AccountRole')
    op.add_column('HealthData', sa.Column('HyperTension', sa.Boolean(), nullable=True))
    op.alter_column('HealthData', 'UserID',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('HealthData', 'Hypertension')
    op.alter_column('Permission', 'PermissionName',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_index(op.f('PermissionName'), table_name='Permission')
    op.alter_column('Prediction', 'HealthDataID',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('Prediction', 'StrokeChance',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.Numeric(precision=4, scale=2),
               existing_nullable=True)
    op.alter_column('Prediction', 'DiabetesChance',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.Numeric(precision=4, scale=2),
               existing_nullable=True)
    op.alter_column('Prediction', 'CVDChance',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.Numeric(precision=4, scale=2),
               existing_nullable=True)
    op.alter_column('Recommendation', 'HealthDataID',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index(op.f('idx_recommendation_healthdata'), table_name='Recommendation')
    op.drop_constraint(op.f('fk_recommendation_healthdata'), 'Recommendation', type_='foreignkey')
    op.create_foreign_key(None, 'Recommendation', 'HealthData', ['HealthDataID'], ['HealthDataID'])
    op.alter_column('UserAccount', 'Email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('UserAccountValidationToken', 'ValidationToken',
               existing_type=mysql.VARCHAR(length=999),
               type_=sa.String(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('UserAccountValidationToken', 'ValidationToken',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=999),
               existing_nullable=False)
    op.alter_column('UserAccount', 'Email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'Recommendation', type_='foreignkey')
    op.create_foreign_key(op.f('fk_recommendation_healthdata'), 'Recommendation', 'HealthData', ['HealthDataID'], ['HealthDataID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index(op.f('idx_recommendation_healthdata'), 'Recommendation', ['HealthDataID'], unique=False)
    op.alter_column('Recommendation', 'HealthDataID',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('Prediction', 'CVDChance',
               existing_type=sa.Numeric(precision=4, scale=2),
               type_=mysql.DECIMAL(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('Prediction', 'DiabetesChance',
               existing_type=sa.Numeric(precision=4, scale=2),
               type_=mysql.DECIMAL(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('Prediction', 'StrokeChance',
               existing_type=sa.Numeric(precision=4, scale=2),
               type_=mysql.DECIMAL(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('Prediction', 'HealthDataID',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_index(op.f('PermissionName'), 'Permission', ['PermissionName'], unique=True)
    op.alter_column('Permission', 'PermissionName',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.add_column('HealthData', sa.Column('Hypertension', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.alter_column('HealthData', 'UserID',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('HealthData', 'HyperTension')
    op.create_index(op.f('RoleName'), 'AccountRole', ['RoleName'], unique=True)
    op.alter_column('AccountRole', 'RoleName',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
