"""Add PatientRequestToken table

Revision ID: b1d8c21fe405
Revises: 27b8726914b4
Create Date: 2026-05-02 15:31:29.028523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1d8c21fe405'
down_revision: Union[str, Sequence[str], None] = '27b8726914b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PatientRequestToken',
    sa.Column('TokenID', sa.Integer(), nullable=False),
    sa.Column('MerchantID', sa.Integer(), nullable=False),
    sa.Column('PatientID', sa.Integer(), nullable=False),
    sa.Column('Token', sa.String(length=999), nullable=False),
    sa.Column('ExpiresAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['MerchantID'], ['UserAccount.UserID'], ),
    sa.ForeignKeyConstraint(['PatientID'], ['Patient.PatientID'], ),
    sa.PrimaryKeyConstraint('TokenID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PatientRequestToken')
    # ### end Alembic commands ###
