"""Remove unused tables

Revision ID: d5c83d9c9af7
Revises: c173c206403b
Create Date: 2026-05-24 18:37:06.230856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd5c83d9c9af7'
down_revision: Union[str, Sequence[str], None] = 'c173c206403b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RolePermission')
    op.drop_table('Permission')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Permission',
    sa.Column('PermissionID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('PermissionName', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('PermissionID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('RolePermission',
    sa.Column('RoleID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('PermissionID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('AssignedAt', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['PermissionID'], ['Permission.PermissionID'], name=op.f('RolePermission_ibfk_1')),
    sa.ForeignKeyConstraint(['RoleID'], ['AccountRole.RoleID'], name=op.f('RolePermission_ibfk_2')),
    sa.PrimaryKeyConstraint('RoleID', 'PermissionID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
