"""Add marital and working status to patient

Revision ID: d89af5748b27
Revises: b1d8c21fe405
Create Date: 2026-05-15 22:18:17.182065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd89af5748b27'
down_revision: Union[str, Sequence[str], None] = 'b1d8c21fe405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Patient', sa.Column('MaritalStatus', sa.Integer(), nullable=True))
    op.add_column('Patient', sa.Column('WorkingStatus', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Patient', 'WorkingStatus')
    op.drop_column('Patient', 'MaritalStatus')
    # ### end Alembic commands ###
