"""Add AuditLog Table

Revision ID: f74fa5de82a1
Revises: 8184ee23453b
Create Date: 2026-03-12 21:13:24.705302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f74fa5de82a1'
down_revision: Union[str, Sequence[str], None] = '9fc0998ce231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AuditLog',
                    sa.Column('LogID', sa.Integer, primary_key=True),
                    sa.Column('EventType', sa.String(50), nullable=False),
                    sa.Column('Success', sa.Boolean, nullable=False),
                    sa.Column('UserID', sa.Integer,
                              sa.ForeignKey('UserAccount.UserID')),
                    sa.Column('UserEmail', sa.String(255)),
                    sa.Column('IPAddress', sa.String(40)),
                    sa.Column('Device', sa.String(255)),
                    sa.Column('Description', sa.Text),
                    sa.Column('CreatedAt', sa.DateTime,
                              server_default=sa.text('CURRENT_TIMESTAMP')),
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AuditLog')
    # ### end Alembic commands ###
